### ISSUE TITLE
compatibilité

### ISSUE THREAD

**Issue by 1000i100** [bjansen/IDEALeek#35]
Bonjour, serait-il possible de packager le plugin de manière à ce qu'il soit compatible avec tout les ide jetbrains (et webstorm en particulier dans mon cas) et pas uniquement avec intelliJ ?

**Comment by bjansen** [comment]
Je viens de pousser une nouvelle release qui permet d'installer le plugin sur les autres IDE, elle est en attente d'approbation par JetBrains.
Par contre, en la testant, je me suis aperçu qu'on ne peut pas faire grand chose avec, car le plugin n'arrive plus à se connecter au serveur LeekWars. En revanche, j'ai remarqué qu'ils ont développé une API permettant d'éditer des scripts en dehors du site, ce qui est très intéressant dans notre cas, mais demanderait pas mal de travail si la décision était prise d'intégrer cette API.

Tout dépend de combien de personnes sont intéressées par ce plugin ;-)

**Comment by bjansen** [comment]
(pour info, http://leekwars.com/help/api )

**Comment by GammaNu** [comment]
avec moi, nous somme pour l'instant 2 ;)

Merci pour le liens vers l'api ! si j'ai le temps je me ferais des git-hook pour pousser mon code sur leekwars à chaque push.

**Comment by bjansen** [comment]
Tout ça a été corrigé dans la version 1.2.0 du plugin. La compatibilité avec les différents IDE est disponible ici : https://plugins.jetbrains.com/plugin/7531-leekscript/update/59866
