### ISSUE TITLE
parser issue : double function call does not work

### ISSUE THREAD

**Issue by machidoine** [bjansen/IDEALeek#36]
**Plugin version** : commit 36bdda3ab405a629bfc930aa525f610f8a7dfc38 (I cloned the repo, compiled and installed the plugin)

**Issue**
This code is not parsed correctly, whereas it work in leekwars.com :
```
function b() {
    return "test";
}

function a() {
    return b;
}
a()();             <--- error here, but it's a legal instruction

```

**Workaround**

```
function b() {
    return "test";
}

function a() {
    return b;
}

var fb = a();
fb();
```

**Comment by bjansen** [comment]
Fixed, thanks for reporting the problem :)
