### ISSUE TITLE
Can't connect to LeekWars server: Please configure the LeekScript plugin

### ISSUE THREAD

**Issue by YohanAlard** [bjansen/IDEALeek#37]
Hi bjansen,

is it still working on 2019 ?  
i could not connect to leekwars with my credential (no proxy)

**Comment by Quidam74** [comment]
same here, up !

**Comment by YohanAlard** [comment]
You should fork and do the job.
project is on hold.

**Comment by bjansen** [comment]
Fixed in 378d40c6ffd67b78373cfde7e04cc73eff538ddc

**Comment by bjansen** [comment]
I published version 1.2.2 of the plugin, which is being reviewed by JetBrains. Your IDE should see the update within two days.
